### ISSUE TITLE
.zip File isnt working in sw5.34

### ISSUE THREAD

**Issue by leseaw** [tinect/TinectOptimusOptimizer#1]
Hi :)

i want to use this plugin, downlod .zip
and upload in sw5.34
SW says, isnt a plugin in the .zip.
My error or SW wrong?

**Comment by tinect** [comment]
Sorry, my fault. Release isn't correct for plugin manager.
Please extract and upload content in folder: custom/plugins/TinectOptimusOptimizer

so the file is accessible: custom/plugins/TinectOptimusOptimizer/TinectOptimusOptimizer.php

**Comment by leseaw** [comment]
new .zip is working :)
